from crewai import Agent, Crew, Process, Task
from crewai.project import CrewBase, agent, crew, task

# If you want to run a snippet of code before or after the crew starts,
# you can use the @before_kickoff and @after_kickoff decorators
# https://docs.crewai.com/concepts/crews#example-crew-class-with-decorators


@CrewBase
class DevCrew:
    """Dev Crew"""

  
    # If you would lik to add tools to your crew, you can learn more about it here:
    # https://docs.crewai.com/concepts/agents#agent-tools
    @agent
    def junior_python_developer(self) -> Agent:
        return Agent(
            role="Junior Python Developer",
            goal="write python code solution without python type hints and pydocs for this problem '{problem}'",
            backstory="You have 3 years python web development experience you know how to use flask, django",
        )

    @agent
    def senior_python_developer(self) -> Agent:
        return Agent(
            role="Senior Python Developer",
            goal="""Review the python code generated by junior_python_developer for this problem '{problem}'
            apply python type hints 
            apply pydocs
            write three pytests for the code""",
            backstory="""You have 20 years experience in Machine Learning, Deep Learning, Generative AI and Agentic AI
            You have good commands on crewai, langgraph and autogen""",
                )
    

    # To learn more about structured task outputs,
    # task dependencies, and task callbacks, check out the documentation:
    # https://docs.crewai.com/concepts/tasks#overview-of-a-task
    @task
    def write_code(self) -> Task:
        return Task(
            description="""you have to write python solution without python type hints and pydocs for this problem '{problem}'""",
            expected_output="return python code only",
            agent=self.junior_python_developer,
        )
    
    @task
    def review_code(self) -> Task:
        return Task(
            description="""you have to review the python code generated by junior_python_developer.
            apply python type hints
            apply pydocs
            apply 3 pytest tests for the code""",
            expected_output="return python code only",
            agent=self.senior_python_developer
        )

    @crew
    def crew(self) -> Crew:
        """Creates the Research Crew"""
        # To learn how to add knowledge sources to your crew, check out the documentation:
        # https://docs.crewai.com/concepts/knowledge#what-is-knowledge

        return Crew(
            agents=self.agents,  # Automatically created by the @agent decorator
            tasks=self.tasks,  # Automatically created by the @task decorator
            process=Process.sequential,
            verbose=True,
        )
