describe_topic:
  description: >
    "We are mentoring to create the best Agentic AI Engineers. Today we teach {topic}"
  expected_output: >
    "The sutends will have mastered the topic {topic}"
  agent: "sirzia"